---
name: HPE Smart Storage Monitor 
slug: hpssacli_monitor
version: 0.1.1-6
description: This is a Docker container for ps3netsrv (or ps3netsvr).
url: https://github.com/d-two/hassio-addons/tree/main/ps3netsrv
startup: application
init: false
hassio_api: true
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
boot: auto
map:
- media:rw
full_access: true
privileged:
  - SYS_RAWIO
schema:
  mqtt_host: str?
  mqtt_username: str?
  mqtt_password: password?
  mqtt_port: str?
  mqtt_topic: str?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
services:
  - mqtt:want